### ISSUE TITLE
Didn't work with python 3.12

### ISSUE THREAD

**Issue by dsiggi** [yaqwsx/pcbnewTransition#6]
Hi,
gentoo just rolled out python 3.12. With this version I can't install pcbnewTransition.

```
...
>> Compiling source in /var/tmp/portage/sci-electronics/pcbnewTransition-0.4.1/work/pcbnewTransition-0.4.1 ...
 * python3_12: running distutils-r1_run_phase distutils-r1_python_compile
 *   Building the wheel for pcbnewTransition-0.4.1 via setuptools.build_meta:__legacy__
python3.12 -m gpep517 build-wheel --prefix=/usr --backend setuptools.build_meta:__legacy__ --output-fd 3 --wheel-dir /var/tmp/portage/sci-electronics/pcbnewTransition-0.4.1/work/pcbnewTransition-0.4.1-python3_12/wheel
2024-06-05 19:13:36,690 gpep517 INFO Building wheel via backend setuptools.build_meta:__legacy__
/var/tmp/portage/sci-electronics/pcbnewTransition-0.4.1/work/pcbnewTransition-0.4.1/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
  LONG_VERSION_PY['git'] = '''
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.12/site-packages/gpep517/__main__.py", line 443, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/gpep517/__main__.py", line 439, in main
    return func(args)
           ^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/gpep517/__main__.py", line 229, in build_wheel
    print(build_wheel_impl(args, args.wheel_dir), file=out)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/gpep517/__main__.py", line 221, in build_wheel_impl
    wheel_name = backend.build_wheel(str(wheel_dir), args.config_json)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 410, in build_wheel
    return self._build_with_temp_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
    self.run_setup()
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 12, in <module>
  File "/var/tmp/portage/sci-electronics/pcbnewTransition-0.4.1/work/pcbnewTransition-0.4.1/versioneer.py", line 1480, in get_version
    return get_versions()["version"]
           ^^^^^^^^^^^^^^
  File "/var/tmp/portage/sci-electronics/pcbnewTransition-0.4.1/work/pcbnewTransition-0.4.1/versioneer.py", line 1412, in get_versions
    cfg = get_config_from_root(root)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/sci-electronics/pcbnewTransition-0.4.1/work/pcbnewTransition-0.4.1/versioneer.py", line 342, in get_config_from_root
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```
I found out that in python 3.12 the function SafeConfigParser()  was removed from configparser:
[https://github.com/jdidion/atropos/issues/135](https://github.com/jdidion/atropos/issues/135)

**Comment by yaqwsx** [comment]
I just fixed this via c01829807de18cddc6d735d04bab5fafa67dd95f
